In [5]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [6]:
import numpy as np

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.shape

(2, 3)

## ravel
- Flattened input array  
- Changing the raveled array changes the parent also

In [8]:
data = arr.ravel()
data.shape
data

(6,)

array([1, 2, 3, 4, 5, 6])

In [9]:
data[2] = 33
data
arr

array([ 1,  2, 33,  4,  5,  6])

array([[ 1,  2, 33],
       [ 4,  5,  6]])