In [7]:
import numpy as np
import math as m

In [8]:
def Rx(theta):
  return np.matrix([[ 1, 0           , 0           ],
                   [ 0, m.cos(theta),-m.sin(theta)],
                   [ 0, m.sin(theta), m.cos(theta)]])
  
def Ry(theta):
  return np.matrix([[ m.cos(theta), 0, m.sin(theta)],
                   [ 0           , 1, 0           ],
                   [-m.sin(theta), 0, m.cos(theta)]])
  
def Rz(theta):
  return np.matrix([[ m.cos(theta), -m.sin(theta), 0 ],
                   [ m.sin(theta), m.cos(theta) , 0 ],
                   [ 0           , 0            , 1 ]])

In [32]:
phi = 0 # roll
theta = m.pi/4 # pitch
psi = m.pi/2 # yaw
print("phi =", phi)
print("theta  =", theta)
print("psi =", psi)

phi = 0
theta  = 0.7853981633974483
psi = 1.5707963267948966


In [33]:
# ypr
R = Rz(psi) * Ry(theta) * Rx(phi)
print(np.round(R, decimals=2))

[[ 0.   -1.    0.  ]
 [ 0.71  0.    0.71]
 [-0.71  0.    0.71]]


In [34]:
# rpy
# 0yx
v1 = np.array([[0],[0],[np.deg2rad(30)]])

In [35]:
v2 = R * v1
print(np.round(v2, decimals=2))
np.rad2deg(v2)

[[0.  ]
 [0.37]
 [0.37]]


matrix([[1.29893408e-15],
        [2.12132034e+01],
        [2.12132034e+01]])