In [5]:
import numpy as np

# Dot Product

![](images/dot_product.png)

In [6]:
v1 = np.array([1, 2])
v2 = np.array([1, 2]).T
p = v1.dot(v2)
print(p)

5


In [7]:
v1 = np.array([[1, 2], [3, 4]])
v2 = np.array([1, 2]).T
p = v1.dot(v2)
print(p)

[ 5 11]


In [8]:
v1 = np.array([[1, 2], [3, 4]])
v2 = np.array([[1, 2],[3, 4]])
p = v1.dot(v2)
print(p)

[[ 7 10]
 [15 22]]


# Identity matrix


In [9]:
I3 = np.identity(3, dtype=int)
print(I3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# Inverse

![](images/inverse.png)

In [10]:
m = np.array([[1, 2], [3, 4]], dtype=int)
m1 = np.linalg.inv(m)
print(m1)

[[-2.   1. ]
 [ 1.5 -0.5]]


![](images/dot_inverse.png)

In [11]:
I = m.dot(m1)
print(I)
I = m1.dot(m)
print(I)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]
[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]
